services:
  php:
    image: dwchiang/nginx-php-fpm:8.2.5-fpm-alpine3.17-nginx-1.24.0
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2G"
    ports:
      - "81:80"
    volumes:
      - "./php:/var/www/html"
      - "./php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./php/default.conf:/etc/nginx/conf.d/default.conf"
      - "./php/nginx.conf:/etc/nginx/nginx.conf"
  node:
    image: node:latest
    working_dir: "/usr/app"
    command: "node index.mjs"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2G"
    ports:
      - "82:80"
    volumes:
      - "./node:/usr/app"
  java_threads:
    image: amazoncorretto:20
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2G"
    working_dir: "/usr/app"
    command: "java --enable-preview -jar app.jar"
    ports:
      - "83:8080"
    volumes:
      - "./java-threads/target/demo-0.0.1-SNAPSHOT.jar:/usr/app/app.jar"
  java_vthreads:
    image: amazoncorretto:20
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2G"
    working_dir: "/usr/app"
    command: "java --enable-preview -Xmx1700M -jar app.jar"
    ports:
      - "84:8080"
    volumes:
      - "./java-vthreads/target/demo-0.0.1-SNAPSHOT.jar:/usr/app/app.jar"
